version: '2.1'

networks:
 test:

services:
 explorerdb.example.com:
   image: hyperledger/explorer-db:latest
   container_name: explorerdb.example.com
   hostname: explorerdb.example.com
   environment:
     - DATABASE_DATABASE=fabricexplorer
     - DATABASE_USERNAME=hppoc
     - DATABASE_PASSWORD=password
   healthcheck:
     test: "pg_isready -h localhost -p 5432 -q -U postgres"
     interval: 30s
     timeout: 10s
     retries: 5
   volumes:
     - ./pgdata:/var/lib/postgresql/data
   networks:
     - test

 explorer.example.com:
   image: hyperledger/explorer:latest
   container_name: explorer.example.com
   hostname: explorer.example.com
   environment:
     - DATABASE_HOST=explorerdb.example.com
     - DATABASE_DATABASE=fabricexplorer
     - DATABASE_USERNAME=hppoc
     - DATABASE_PASSWD=password
     - LOG_LEVEL_APP=debug
     - LOG_LEVEL_DB=debug
     - LOG_LEVEL_CONSOLE=info
     - LOG_CONSOLE_STDOUT=true
     - DISCOVERY_AS_LOCALHOST=false
   volumes:
     - ./config.json:/opt/explorer/app/platform/fabric/config.json
     - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
     - ../basic-network/organizations:/tmp/crypto
     - ./wallet:/opt/explorer/wallet
   ports:
     - 18080:8080
   depends_on:
     explorerdb.example.com:
       condition: service_healthy
   networks:
     - test
